# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
        - main
  pull_request:
      branches:
        - main


jobs:
 
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy File to Destination Repository
      run: |
        cp "server.js" "Vedashree-Ekbote/cicd-target"
    - name: Use Node.js ${{ matrix.node-version }}
     # uses: actions/setup-node@v2
      #with:
       # node-version: '14'
        #cache: 'npm'
        
    #- run: npm install
      run: |
        git config --global user.name "Vedashree-Ekbote"
        git config --global user.email "vedashree.ekbote10@gmail.com"
        git add .
        git commit -m "Send file to another repository"
        git push
  

 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
